import * as PIXI from 'pixi.js';

export const types = {
  Ani: 'Ani_mc',
  Arancar: 'Arancar_mc',
  Beggar: 'Beggar_mc',
  Bitten: 'Bitten_mc',

  Boffin: 'Boffin_mc',
  Butcher: 'Butcher_mc',
  Clown: 'Clown_mc',
  Director: 'Director_mc',
  Doll: 'Doll_mc',
  HappyImp: 'HappyImp_mc',
  HeadZombie: 'HeadZombie_mc',
  Iceman: 'Iceman_mc',
  Liprikon: 'Liprikon_mc',
  MasqueradeV1: 'MasqueradeV1_mc',
  Menos: 'Menos_mc',
  Mutant_mc0019: 'Mutant_mc',
  MasqueradeV2: 'MasqueradeV2_mc',
  PatchKiss: 'PatchKiss_mc',
  Possessed: 'Possessed_mc',
  Rambo: 'Rambo_mc',
  Scarecrow: 'Scarecrow_mc',
  Vampire: 'Vampire_mc',
  Vampiressa: 'Vampiressa_mc',
  Werewolf: 'Werewolf_mc',
  Witch: 'Witch_mc',
  Wonk: 'Wonk_mc',
  YukiOnna: 'YukiOnna_mc',
  ZBarbarian: 'ZBarbarian_mc',
  ZCyborg: 'ZCyborg_mc',
  ZFire: 'ZFire_mc',
  ZombieElectro: 'ZombieElectro_mc',
  ZombieLab: 'ZombieLab_mc',
  ZombieV2: 'ZombieV2_mc',
  ZombieV3: 'ZombieV3_mc',
  ZombieV5: 'ZombieV5_mc',
  ZombieV5Kiss: 'ZombieV5Kiss_mc',
  ZombieV6: 'ZombieV6_mc',
  ZRasta: 'ZRasta_mc',
  Kiss: 'Kiss_mc',
  ZWoman2: 'ZWoman2_mc',
  ZWoman: 'ZWoman_mc',

  Patch: 'Patch_mc',
  Jester: 'ZJester_mc',
  Fire: 'ZFire_mc',
  Woman: 'ZWoman_mc',
  ZombieV5: 'ZombieV5_mc',
  ZombieV6: 'ZombieV6_mc',
  Zombie: 'zombie_mc',
};

const Names = {
  Patch_mc: 20,
  ZJester_mc: 80,
  Ani_mc: 20,
  Arancar_mc: 40,
  Beggar_mc: 20,
  Bitten_mc: 20,

  Boffin: 20,
  Butcher: 20,
  Clown: 80,
  Director: 40,
  Doll: 80,
  HappyImp: 40,
  HeadZombie: 40,
  Iceman: 40,
  Liprikon: 40,
  MasqueradeV1: 40,
  Menos: 14,
  Mutant_mc0019: 20,
  MasqueradeV2: 40,
  PatchKiss: 20,
  Possessed: 20,
  Rambo: 40,
  Scarecrow: 40,
  Vampire: 20,
  Vampiressa: 20,
  Werewolf: 20,
  Witch: 20,
  Wonk: 40,
  YukiOnna: 40,
  ZBarbarian: 20,
  ZCyborg: 20,
  ZFire: 40,
  ZombieElectro: 20,
  ZombieLab: 40,
  ZombieV2: 20,
  ZombieV3: 39,
  ZombieV5: 20,
  ZombieV5Kiss: 20,
  ZombieV6: 20,
  ZRasta: 20,
  Kiss: 20,
  ZWoman2: 20,
  ZWoman: 20,
};

export function getTexture(type) {
  const listNames = [];
  const textureArray = [];
  for (let i = 0; i < Names[type]; i++) {
    const textureName = `${type}${i < 10 ? '000' : '00'}${i}`;
    textureArray.push(PIXI.Texture.from(textureName));
  }

  return textureArray;
}
