import * as PIXI from 'pixi.js';

export const eventEmitter = new PIXI.utils.EventEmitter();
export const EVENTS = {
  SET_SCREEN: 'SET_SCREEN',
  NEW_GAME_CONTROLLER: 'NEW_GAME_CONTROLLER',
  NEW_GAME_VIEW: 'NEW_GAME_VIEW',
  CONTINUE_GAME: 'CONTINUE_GAME',
  LEVEL_COMPLETE: 'LEVEL_COMPLETE',
  CLEAN_GAME: 'CLEAN_GAME',
  PAY_TRAP: 'PAY_TRAP',
  ADD_TRAP: 'ADD_TRAP',
  UPDATE_GOLD: 'UPDATE_GOLD',
  RETURN_GOLD: 'RETURN_GOLD',
  UPDATE_HEALTH: 'UPDATE_HEALTH',
  CREATE_ENEMY: 'CREATE_ENEMY',
  ENEMY_HAS_COME: 'ENEMY_HAS_COME',
  ENEMY_DEATH: 'ENEMY_DEATH',
  UPDATE: 'UPDATE',
  REMOVE_TRAP: 'REMOVE_TRAP',
};
