export const config = {
  mobileWidth: 640,
  mobileHeight: 1136,
  defaultWidth: 640,
  defaultHeight: 1136,
  MAP_WIDTH_MAX: 35,
  MAP_HEIGHT_MAX: 20,
  MAP_CELL_SIZE: 32,
  MAP_CELL_HALF: 16,
  STATE_IDLE: 1,
  STATE_ATTACK: 2,
  STATE_CELL_FREE: 0,
  STATE_CELL_BUSY: 1,
  panel_text: {
    fontFamily: 'Helvetica',
    fontSize: 25,
    fontWeight: 'bold',
    fill: 0x8159c1,
    align: 'center',
    wordWrap: true,
    wordWrapWidth: 400,
  },

  STATE_SCREEN_GAME: 1,
  STATE_SCREEN_LOBBY: 2,
  STATE_SCREEN_PAUSE: 3,
  STATE_SCREEN_START_GAME: 4,
  STATE_SCREEN_START_GAME: 5,
  STATE_SCREEN_YOU_WIN: 6,

  TYPE_RAKE: 3,
  TYPE_SHEEP: 2,
  TYPE_FENCE: 1,
};
