export const config = {
  mobileWidth: 640,
  mobileHeight: 1136,
  defaultWidth: 640,
  defaultHeight: 1136,
  MAP_WIDTH_MAX: 35,
  MAP_HEIGHT_MAX: 20,
  MAP_CELL_SIZE: 32,
  MAP_CELL_HALF: 16,
  STATE_IDLE: 1,
  STATE_ATTACK: 2,
  STATE_CELL_FREE: 0,
  STATE_CELL_BUSY: 1,
  panel_text: {
    fontFamily: 'Helvetica',
    fontSize: 25,
    fontWeight: 'bold',
    fill: 0x8159c1,
    align: 'center',
    wordWrap: true,
    wordWrapWidth: 400,
  },

  STATE_SCREEN_GAME: 1,
  STATE_SCREEN_LOBBY: 2,
  STATE_SCREEN_GAME_OVER: 3,
  STATE_SCREEN_WIN: 3,
  STATE_SCREEN_LEVELS: 4,

  TRAP_RAKE: 3,
  TRAP_SHEEP: 2,
  TRAP_FENCE: 1,

  ENEMY_MAX_Y: 1136 - 150,
};
